### ISSUE TITLE
Error running simple scan

### ISSUE THREAD

**Issue by Sydwicked** [21y4d/nmapAutomator#12]
Starting Nmap 7.80 ( https://nmap.org ) at 2020-01-11 10:15 IST
./nmapAutomator.sh: line 138:  1528 Segmentation fault      $nmapType -sCV -p`echo "${basicPorts}"` -oN nmap/Basic_$1.nmap $1

**Comment by 21y4d** [comment]
This is related to nmap, not the script itself..
Thanks for the note..
