### ISSUE TITLE
sudo issue on nmap

### ISSUE THREAD

**Issue by techn0tr0ll** [21y4d/nmapAutomator#18]
Hey 21y4d

i encountered some weird problems ... while running a quick scan with your tool, sudo must not be entered, otherwise nmap will do a more complex scan [1] but for udp scans for example, nmap needs sudo to execute...

is there already a work around for this problem?
otherwise it would probably the easiest way, to add another "nmapType" variable... one w/o sudo and one with sudo, so the udp scan can be conducted with the needed privs

**Comment by 21y4d** [comment]
Thank you for reporting this.
I used to run this tool as root, which should not be different than running it with sudo as another user.
I'll look into it to see if some thing can be done to make easier to use.

**Comment by 21y4d** [comment]
Could not replicate the issue, so couldn't identify its cause to fix it.
