### ISSUE TITLE
Nikto Scan Time

### ISSUE THREAD

**Issue by harr-sudo** [21y4d/nmapAutomator#19]
Having run the tool a couple of times on different targets, I have found the Nikto scan to be excessively long. 

Where can we edit the code to set a max time of 600 seconds for example?

(set flag "-maxtime 600")

Thanks

**Comment by 21y4d** [comment]
On line [344](https://github.com/21y4d/nmapAutomator/blob/7c2175dae8fb2aad4516287ebd609fa293dea747/nmapAutomator.sh#L344) and 347 [https://github.com/21y4d/nmapAutomator/blob/7c2175dae8fb2aad4516287ebd609fa293dea747/nmapAutomator.sh#L347](url).. just add it before `-host`
