### ISSUE TITLE
Port specifications are illigal error on all scans after Quick scan.

### ISSUE THREAD

**Issue by sleepingspy999** [21y4d/nmapAutomator#24]
On running any scans after quick scan, all other scans have this error.
Running on kali 2020.2
Latest nmap ver.
used to work.
Get same ports error on all scans.Error #485: Your port specifications are illegal.  Example of proper form: "-100,200-1024,T:3000-4000,U:60000-"
QUITTING!

---------------------Starting Nmap Basic Scan---------------------
                                                                                                                                      
Host discovery disabled (-Pn). All addresses will be marked 'up' and scan times will be slower.
Starting Nmap 7.91 ( https://nmap.org ) at 2020-11-23 08:15 GMT
Error #485: Your port specifications are illegal.  Example of proper form: "-100,200-1024,T:3000-4000,U:60000-"
QUITTING!

**Comment by KatsuragiCSL** [comment]
Cannot reproduce. What target did you scan? Have you tried it at 1.1.1.1?

**Comment by 21y4d** [comment]
Tested the script with latest Kali and nmap, and it seems to run fine. Please let me know if the issue persists.
