### ISSUE TITLE
Not able to run from Another script

### ISSUE THREAD

**Issue by progerscs** [21y4d/nmapAutomator#29]
I am trying to create a script that calls nmapAutomator and then autorecon. When I try to to run the main script it will not run nmapAutomator.
Also I edited my version of the script to be able to tell it to output to a specific folder and not to the current folder.
Here are some screen shots of the code I have tried.
Any suggestions?

![image](https://user-images.githubusercontent.com/62584036/106229227-5e569800-61aa-11eb-9d18-f96d8e956890.png)
![image](https://user-images.githubusercontent.com/62584036/106229273-79c1a300-61aa-11eb-972f-6c0fafcb91e2.png)
![image](https://user-images.githubusercontent.com/62584036/106229305-8cd47300-61aa-11eb-80fb-302211133d0a.png)

**Comment by 21y4d** [comment]
This is not an issue related to nmspAutomator.
