### ISSUE TITLE
 /bin/bash: line 1: gobuster: command not found  Finished gobuster scan

### ISSUE THREAD

**Issue by jmarshall7** [21y4d/nmapAutomator#4]
The script will not run the gobuster portion. I took a look at the gobuster repo to see if there were any issues related and I did not come across any. I followed your installation steps. any recommendations on how to mitigate this? Really love the script!

**Comment by giant372** [comment]
May be a stupid question, but do you have gobuster installed?

**Comment by jmarshall7** [comment]
Hey @giant372 yes I followed the  instructions located in the readme file specifically I ran 
```apt-get update
apt-get install gobuster --only-upgrade```

**Comment by giant372** [comment]
Just use `apt-get install gobuster`
--only-upgrade does just that. does not install the tool, just upgrades it if its already there

**Comment by 21y4d** [comment]
If you already have gobuster 2.0, use the command with --only-upgrade, otherwise use:
```apt-get install gobuster```
