### ISSUE TITLE
Adding Output option?

### ISSUE THREAD

**Issue by progerscs** [21y4d/nmapAutomator#41]
I have been using an output option to my version of the script. That way you can say where you want the output to go. In case you are wanting to run this script and autorecon and have them both go to the same folder.
Is this something that people would want in the script?

**Comment by 21y4d** [comment]
Currently it defaults to a folder named as the host name/up. But I guess it'd be nice if that's the default and users have the option to change it.

**Comment by 21y4d** [comment]
I added changing the output folder as a planned feature, i'll work on it, and pull requests are welcome of course :)

To be clear, this would only change the output folder path/name, and not of every single output. This will still be in the nmap/recon folders, or the logic of the script would break.

**Comment by 21y4d** [comment]
I added this feature, as it only required changing a single line :)
