### ISSUE TITLE
POSIX amelioration didn't work on Manjaro 20

### ISSUE THREAD

**Issue by lx6XC** [21y4d/nmapAutomator#49]
Hello, following the POSIX improvement, the recon phase does not work on Manjaro 20. For that, you have to rollback to "read -t 1 reconCommand"  on line 543.

**Comment by 21y4d** [comment]
The script proved to work under Manjaro 20 if you use bash, zsh, or sh.
Try calling it with 'bash nmapAutomator.sh'
