### ISSUE TITLE
.nmap files crashing cherrytree

### ISSUE THREAD

**Issue by ightnapovial** [21y4d/nmapAutomator#52]
At some point in the past year or so the output files for nmap were renamed to end in ".nmap" instead of ".txt". It seems cherrytree is incompatible with the .nmap file extension (or it is expecting different data than what it's given) since when trying to import these files it now completely crashes cherrytree. If I edit nmapAutomator.sh and replace all instances of ".nmap" with ".txt" cherrytree can import the files without incident (also works if you rename the files after the script finishes).

Can we revert the file extension back to .txt or is there a specific reason they need to be .nmap?

Thanks!

**Comment by 21y4d** [comment]
Hey.. it has always been .nmap

**Comment by ightnapovial** [comment]
Must be mis-remembering or maybe it's a change to cherrytree...

At any rate, is there a technical reason it needs to be .nmap or can it be switched to .txt?

**Comment by 21y4d** [comment]
Not really, nmap defaults to it, but it can be .txt
