### ISSUE TITLE
Unable to run nmapAutomator due to some config issues.

### ISSUE THREAD

**Issue by saurabhj4in** [21y4d/nmapAutomator#56]
I am using Mac (macOS Big Sur 11.4) and unable to run the nmapAutomator script.
Kindly find the below mentioned output when I run the script. 

Running a Script scan on 10.10.10.134

Host is likely running Windows

---------------------Starting Port Scan-----------------------

sed: 1: "/elapsed/{s/.*undergoin ...": bad flag in substitute command: '}'
sed: 1: "/% done/{s/.*About \(.* ...": bad flag in substitute command: '}'
sed: 1: "/elapsed/{s/Stats: \(.* ...": bad flag in substitute command: '}'
sed: 1: "/remaining/{s/.* (\(.*\ ...": bad flag in substitute command: '}'
sed: 1: "/elapsed/{s/.*undergoin ...": bad flag in substitute command: '}'
sed: 1: "/% done/{s/.*About \(.* ...": bad flag in substitute command: '}'                             ] 0% done   
sed: 1: "/elapsed/{s/Stats: \(.* ...": bad flag in substitute command: '}'
sed: 1: "/remaining/{s/.* (\(.*\ ...": bad flag in substitute command: '}'
sed: 1: "/elapsed/{s/.*undergoin ...": bad flag in substitute command: '}'
sed: 1: "/% done/{s/.*About \(.* ...": bad flag in substitute command: '}'                             ] 0% done   
sed: 1: "/elapsed/{s/Stats: \(.* ...": bad flag in substitute command: '}'
sed: 1: "/remaining/{s/.* (\(.*\ ...": bad flag in substitute command: '}'
sed: 1: "/elapsed/{s/.*undergoin ...": bad flag in substitute command: '}'
sed: 1: "/% done/{s/.*About \(.* ...": bad flag in substitute command: '}'                             ] 0% done   
sed: 1: "/elapsed/{s/Stats: \(.* ...": bad flag in substitute command: '}'
sed: 1: "/remaining/{s/.* (\(.*\ ...": bad flag in substitute command: '}'
sed: 1: "/elapsed/{s/.*undergoin ...": bad flag in substitute command: '}'
sed: 1: "/% done/{s/.*About \(.* ...": bad flag in substitute command: '}'                             ] 0% done   
sed: 1: "/elapsed/{s/Stats: \(.* ...": bad flag in substitute command: '}'
sed: 1: "/remaining/{s/.* (\(.*\ ...": bad flag in substitute command: '}'
sed: 1: "/elapsed/{s/.*undergoin ...": bad flag in substitute command: '}'
sed: 1: "/% done/{s/.*About \(.* ...": bad flag in substitute command: '}'                             ] 0% done   
sed: 1: "/elapsed/{s/Stats: \(.* ...": bad flag in substitute command: '}'
sed: 1: "/remaining/{s/.* (\(.*\ ...": bad flag in substitute command: '}'
In progress: No Scan (0:00:00 elapsed - 0:00:00 remaining)   

Please do let me know what can be done to resolve this issue

**Comment by 21y4d** [comment]
Thanks for the report. It looks like sed has different syntax on a Mac, hence it's breaking. This is probably the case with several other tools as well, as the syntax is not universal.

Currently macOS is not supported, and we'll have to test all tools and provide their appropriate syntax when running on a Mac.

**Comment by saurabhj4in** [comment]
Thank you for your response.
