### ISSUE TITLE
How to skip the recon process and how to use multiple types

### ISSUE THREAD

**Issue by naveen12** [21y4d/nmapAutomator#60]
Hi, 
the tool is awesome. could you please provide any changes related to skip recon process, use multiple types

when we use All type it asking last to use recon or skip but the input is not taking properly and it throwing error message
![nmap scan](https://user-images.githubusercontent.com/5235145/152780576-a79b1d9c-b9c7-4515-98f7-7f3ccfb5a460.png)

**Comment by 21y4d** [comment]
To skip you can simply type ! and hit enter
