### ISSUE TITLE
Scanns not working

### ISSUE THREAD

**Issue by nu11s3c** [21y4d/nmapAutomator#61]
I wish I knew how to diagnose the tool a bit better, when I run scans it tells me the host is likely such and such and then the port scans fail. The first install the UDP scan worked,  I deleted and reinstalled exactly according to the instructions in the readme and now none work. I even tried downloading the static nmap and chmod +x it and still doesnt scan. I used this on a prior vm and it worked flawlessly. Any ideas?

**Comment by 21y4d** [comment]
From your description, it seems like an issue with nmap, not the script. Try running it with sudo

**Comment by nu11s3c** [comment]
-Pn switch actually

**Comment by nu11s3c** [comment]
Thanks for your work
