### ISSUE TITLE
This library is attempting to receive an incoming connection from Nmap!

### ISSUE THREAD

**Issue by mkmnstr123** [21y4d/nmapAutomator#69]
I was testing this library and I got a notification that an incoming connection through Nmap... there is no a single case of use for an incoming connection coming from a library like this. Trojan is the best word to describe. Erasing my computer.

**Comment by christiancoleman** [comment]
What? It’s a bash script. You can see all the lines? I’m confused. What are
you talking about?

**Comment by 21y4d** [comment]
As mentioned, this is an open source script so you can go through it and see what it's doing. If you think you've got a trojan, it's likely from something else.

**Comment by mkmnstr123** [comment]
Yeah I know is a bash script, still, the fact is that as soon as it requested to run with sudo permissions for UDP scan I got an alert of an attempt of incoming connection through Nmap. I do not mean to tell any lies, just telling what happened. Wish I took an screenshot.
