### ISSUE TITLE
Export scan

### ISSUE THREAD

**Issue by tXambe** [21y4d/nmapAutomator#8]
Hello,

I will like know how I can export scan in xml or json format.

Thanks and a greeting

**Comment by 21y4d** [comment]
The code is outputting the findings to a txt file, and isn't configured to output in xml or json.

You can easily adjust the nmap parts to output to xml, but this will not cover the recon results.

**Comment by tXambe** [comment]
This files txt are saved in this route --> C:\N-Stalker\Free X\reports  ??

**Comment by 21y4d** [comment]
This is a Bash script, and is only meant to he ran on Linux.

**Comment by tXambe** [comment]
Sorry I mixed tools
