### ISSUE TITLE
Doesn't work on mac (+workaround)

### ISSUE THREAD

**Issue by iodbh** [21y4d/nmapAutomator#9]
Hi, Thanks for the script !

I've been using it on mac and it doesn't work out of the box, because the version of `head` shipped with MacOS doesn't support the arguments used in the script.

The workaround is to install the gnu version of `head` (via homebrew: `brew install coreutils` and to edit the script by either adding `PATH="$(brew --prefix)/opt/coreutils/libexec/gnubin:$PATH"` at the start OR replacing all calls to `head` by calls to `ghead` (see [https://formulae.brew.sh/formula/coreutils](https://formulae.brew.sh/formula/coreutils)).

If you're interested in supporting MacOS, I can send a pull request your way to indicate the extra depency in the README and edit the script accordingly.

**Comment by 21y4d** [comment]
Thanks for the tip.
I designed it mainy for OSCP, and hence for Kali Linux "Debian". It shouldn't be hard to have it work on macOS like you mentioned, but it would be better to have a Mac version as a fork instead of a pull on the original one.

Thanks for sharing..
